// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Base() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html><head><script src=\"https://cdn.tailwindcss.com\"></script><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/uikit@3.19.2/dist/css/uikit.min.css\"><script src=\"https://cdn.jsdelivr.net/npm/uikit@3.19.2/dist/js/uikit.min.js\"></script><script src=\"https://cdn.jsdelivr.net/npm/uikit@3.19.2/dist/js/uikit-icons.min.js\"></script><style>\n    body, html {\n      margin: 0;\n      padding: 0;\n      height: 100%;\n    }\n\n    .uk-card {\n      height: 100%;\n    }\n  </style></head><body><div class=\"uk-light uk-background-secondary uk-card uk-card-secondary uk-card-body tkim-curved\" uk-scrollspy=\"cls: uk-animation-fade; target: .uk-card; delay: 500; repeat: true\"><div class=\"uk-card-header\"><div class=\"uk-grid-small uk-flex-middle\" uk-grid><div class=\"uk-width-expand\"><img class=\"uk-border-circle uk-align-right\" width=\"100\" height=\"100\" src=\"/static/me.jpg\"></div></div></div><dl class=\"uk-description-list uk-description-list-divider\"><dd>Thomas Kim</dd><dd>Sydneysider living in Baden-Württemberg, Germany</dd><dd>MBA (Technology) @ <a href=\"https://www.business.unsw.edu.au/agsm\">Australian Graduate School of Management, UNSW</a></dd><br><dd><b>Current</b></dd><dd>Director (Technology) @ <a href=\"https://mindarc.eu\">MindArc EU GmbH</a></dd><dd><b>Uses</b></dd><dd>JS/TS, Go, Rust, Python, Shell</dd><dt></dt><div class=\"uk-grid-small uk-child-width-auto\" uk-grid><div><a href=\"https://www.linkedin.com/in/tkim86/\" target=\"_blank\" uk-icon=\"linkedin\"></a></div><div><a href=\"https://github.com/tkimmm\" uk-icon=\"github\" target=\"_blank\"></a></div><div><a href=\"https://twitter.com/tkimdotio\" uk-icon=\"twitter\" target=\"_blank\"></a></div></div></dl></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
